### ISSUE TITLE
Switching with numbers?

### ISSUE THREAD

**Issue by sundarv85** [ccampbell/sublime-goto-window#11]
Question/Feature Request:

Would it be possible to switch the window using numbers after pressing `cmd+shift+o`. Is something like that even possible with that pull down menu that sublime offers

**Comment by ccampbell** [comment]
Unfortunately this is not possible. I actually opened up a feature request for a similar feature:

https://forum.sublimetext.com/t/add-keyboard-shortcut-for-selecting-options-in-goto-menu/36500

If you are talking about something different then feel free to clarify. You can also leave a comment there.
