### ISSUE TITLE
To close the window

### ISSUE THREAD

**Issue by sundarv85** [ccampbell/sublime-goto-window#12]
Feature Request:

Would it be possible to close the Window from the goto pop up window itself. When I have multiple projects, and if I would like to close a few.. 

cmd+shift+o -> then with ctrl key pressed when I select a window, that window shall be closed.

Would such a feature be possible?

**Comment by ccampbell** [comment]
Similar to issue #11 you raised, I don’t think this is possible. I agree it would be nice, but I don’t think it’s possible to detect key modifiers from inside the goto menu
