### ISSUE TITLE
1.5 seconds to switch on Mac?

### ISSUE THREAD

**Issue by semihsezer** [ccampbell/sublime-goto-window#14]
First, thank you for such an amazing plugin! I was looking for a better way to manage Sublime windows and this hit the spot. I just discovered it yesterday and I am loving it.

I have about 10-15 windows open on my macbook and I find that switching happens after a 1.5 second delay. I am aware this is not that long, but I am used to windows switching instantly. Is this the case for most people, switching taking 1.5 seconds? Also do you know why this might be or if there is a way to configure it?

I am happy to take a look at the code as well.

**Comment by ccampbell** [comment]
I use it on Mac and thus I am well aware of the delay. Unfortunately, I spent a while on this and I am not sure it is possible to make it faster easily. The relevant code is this bit

https://github.com/ccampbell/sublime-goto-window/blob/102f9ce97dfc61d8092cb3ecd1f47d13329f1dd9/GotoWindow.py#L63-L79

It has to do with SublimeTextIssues/Core#444 which is a bug in Sublime Text where after calling the API method to switch to a different window, it doesn’t actually focus the window. What I came up with is essentially a hack to do it. You can read my replies in that ticket.

It may be possible to make it faster with more advanced AppleScript commands, but as I explained there, on recent MacOS versions you may have to give Sublime Text special permission to execute those where I wanted to find a solution that worked out of the box.

**Comment by ccampbell** [comment]
As part of fixing another bug related to this plugin on MacOS Big Sur (fe23342f896cac3b34b9a78256df9e822b52df91), I was able to also remove the delay in the script (if you are running MacOS 11 or greater) and it appears to be quite a bit faster now too. Going to close this ticket
