### ISSUE TITLE
Window not switching in MacOS Big Sur 11.1 (Sublime 3.2.2)

### ISSUE THREAD

**Issue by javistuff** [ccampbell/sublime-goto-window#15]
Hey everyone!

This may be useless now that I see that it's been a while since this repo was last updated, but this package isn't working on my end right now (worked beautifully for years).

I'm on Sublime 3.2.2. When called, the input shows up with all open windows available and I can write or select the window I want to go to. Done that, the current window loses focus, but the selected window doesn't come up.

Am I the only one seeing this?

I'm in MacOS Big Sur, version 11.1, if that matters.

Thanks!

**Comment by javistuff** [comment]
Forgot to mention... THANKS for this AMAZING package. It's been a life saver for years. 🙏

**Comment by ccampbell** [comment]
Thanks for reporting it. I actually just ran into this myself the other day for the first time. After quitting and reopening Sublime Text it started working again for me. Can you try that? I’m not sure exactly what is causing it, but I am also on MacOS Big Sur 11, and I never had any issues before that 😕

**Comment by javistuff** [comment]
Hey Craig! Thanks for replying :)

Nope... did that too, but just tried it again just in case and it's still behaving the same way. Perhaps it's the amount of open projects on Sublime? I have 13 right now (I know, I know... 🙈).

If it helps, it always worked perfectly up until a month ago or so.

**Comment by ccampbell** [comment]
That’s not so many. I’ve had 40 or 50 open before heh. That’s why I made this package in the first place. I haven’t had any issues lately, but I’m running Big Sur 11.01 not 11.1 so it’s possible that something may have changed there that broke it. I’m not sure. Can you try uninstalling and reinstalling the go to window package just to see if that helps. Also maybe restarting your computer itself just to see?

**Comment by javistuff** [comment]
Will try not to get to that number, but that's reassuring 😂

Tried that too a few days ago. Removed and reinstalled the package in case something was updated and I missed it, and also restarted the computer. Still no luck.

If I come up with anything different I'll let you know.

**Comment by mcoppola** [comment]
Hey all, I am also experiencing this issue with osx 11.1.  Also want to add my appreciation for this package!  Let me know if I can provide anything for debugging.

**Comment by ccampbell** [comment]
Aye. Thanks. I guess I may have to upgrade to 11.1 to test this out. Is there any error in the console when you try to switch?

```
View -> Show Console
```

I wonder if the AppleScript is no longer allowed to run without giving Sublime extra privileges. You can try:

1. Go into System Preferences -> Security & Privacy -> Accessibility
2. Add Sublime Text to the list of apps and make sure it is checked

**Comment by javistuff** [comment]
Thanks for keeping an eye on this, Craig!

Just tested that. Nothing on the console when I try switching windows (or after that).

And tried adding Sublime to both the Accessibility permissions panel, and the Input Monitoring one (as I recently had to do something similar for another app) but again, nothing yet.

**Comment by ccampbell** [comment]
Just upgraded to 11.2 and sadly (for me) I *can* reproduce. The first time I tried the command I was prompted because the AppleScript uses the Dock in a hack to switch. 

<img width="252" src="https://user-images.githubusercontent.com/259316/107158811-81c3d480-695a-11eb-94a5-d1a60d676781.png">

But even after saying okay it didn’t work. I will try to find a fix.

**Comment by ccampbell** [comment]
I found a workaround. It makes no sense, but it seems to work. An added bonus is I was able to get rid of the AppleScript delay so it should actually switch a bit faster now as well. I don’t know how long it takes for the official package control channel to pull the update, but hopefully it will see it soon, and then you can confirm it is working again.

**Comment by javistuff** [comment]
YES!!!! It's working! 

That nonsense workaround worked beautifully.

Thank you SO much! Please tell me where can I send you a handful of coffees :)
