### ISSUE TITLE
Doesn't work on Linux (suggestion: use wmctrl)

### ISSUE THREAD

**Issue by deborasetton** [ccampbell/sublime-goto-window#6]
Hi,

I just installed this plugin, and it works great up until the part where I select the window I'd like to focus, and then it doesn't do anything (the selected window is not activated, Sublime just stays right where it was before).

I tracked down the issue to the `focus` function. If I run the code of that function in Sublime Console, it also has no effect. Also, this doesn't seem to be a bug similar to [the OS X one](https://github.com/SublimeTextIssues/Core/issues/444), because if I Alt-Tab out of Sublime and back again, the old window is still the active one.

I have found a very simple workaround which seems to work well: delegate the actual focusing of a window to the underlying window manager, [`wmctrl`](http://linux.die.net/man/1/wmctrl).

Would you be instereted in a patch for this? If so, I'd be happy to submit one for review.

Cheers,
Débora.

**Comment by deborasetton** [comment]
Forgot to mention that I'm running Ubuntu 15.10 (wily), and I don't have access to other Linuxes to confirm that this affects all of them, but I don't think the patch would _hurt_ either, since I saw no noticeable performance decrease due to the call to `wmctrl` using `subprocess.Popen`.

**Comment by ccampbell** [comment]
Yes! Feel free to submit a patch. I do not have a Linux machine to test on but if it is already not working, it isn't going to make things worse. :smile:
