### ISSUE TITLE
Goto Window only works for windows with project folders

### ISSUE THREAD

**Issue by mattst** [ccampbell/sublime-goto-window#8]
### Goto Window only works for windows with project folders

If a window has no project associated with it or if no folders have been added to the project, then Goto Window does not list the window at all.

The problem arises in the method below, since only windows for which `window.folders()` is not an empty list get added.

```
def _get_folders(self):
    folders = []
    home = os.getenv('HOME')
    for i, window in enumerate(sublime.windows()):
        for folder in window.folders():
            if folder.startswith(home):
                folder = folder.replace(home, '~')

            folders.append((folder, i))
```

When a window has no project or a project which has not had folders added to it, then `window.folders()` returns an empty list `[]`.

Also the plugin uses the folder name instead of the project name - and even worse results in the final project folder being used as the text displayed in the overlay. For example if the project file looks like this:

```
{
    "folders":
    [
        {
            "path": "/path/to/MyPlugin"
            "path": "/path/to/icons"
        }
    ]
}
```

Then the window's _name_ in the overlay will be 'icons'.

Instead I suggest you use the `Window` class `project_file_name()` method to get the actual project name, with something like the code below, which is the established way plugin developers get the project name, and will give you the same thing as what ST displays in the title bar of its windows after the file path.

```
# e.g. "/path/to/Projects/My Project Name.sublime-project" --> "My Project Name"

project_file_path = window.project_file_name()
project_file_name = os.path.basename(project_file_path)
project_name = os.path.splitext(project_file_name)[0]
```

Then there would be no need to iterate through `window.folders()` at all.

If there is no project at all in the window then `window.project_file_name()` will return `None`. In these cases then instead of using the project name in the overlay I suggest you use the buffer name of the buffer which is in the active view of the window.

```
active_view_path = window.active_view().file_name()
active_view_filename = os.path.basename(active_view_path)

# Watch out as `window.active_view().file_name()` will return None
# for "untitled" buffers, in which case you could just use "untitled".
```

I hope this helps.

**Comment by johnathanz** [comment]
I use Sublime to make loads of notes on the fly, and could have up to 6 or so windows open. None of which has projects at all. 

When I activate the shortcut key, nothing happens.

May be relate to this issue.

On OSX El Capitan, ST3, Build 3126

**Comment by ccampbell** [comment]
Thanks for the report. @johnathanz same issue. Working on a fix right now
